### ISSUE TITLE
Needs update to distrust WoSign and StartCom [rt.cpan.org #118592]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/Mozilla-CA#1]
Migrated from [rt.cpan.org#118592](https://rt.cpan.org/Ticket/Display.html?id=118592) (status was 'new')

Requestors:
* KENTNL@cpan.org
* dolmen@cpan.org

From kentnl@cpan.org on 2016-11-02 03:46:58
:
```
Mozilla upstream are distrusting these CAs due to some really sketchy
dealings:

 

https://blog.mozilla.org/security/2016/10/24/
distrusting-new-wosign-and-startcom-certificates/

And Mozilla::CA should probably be synced to reflect this.



```

**Comment by genio** [comment]
Closing this issue out as we're now syncing with Mozilla.
