### ISSUE TITLE
Specify license in META [rt.cpan.org #97815]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/Mozilla-CA#6]
Migrated from [rt.cpan.org#97815](https://rt.cpan.org/Ticket/Display.html?id=97815) (status was 'open')

Requestors:
* REHSACK@cpan.org
* dolmen@cpan.org

From rehsack@cpan.org on 2014-08-07 07:36:38
:
```
https://metacpan.org/pod/CPAN::Meta::Spec#license allows being concrete.
Suitable seems to be license => [ qw(mozilla_1_1 gpl_2 lgpl_2_1) ]

Thanks, Jens

```

From skaji@cpan.org on 2018-02-26 13:17:56
:
```
Currently "Invalid LICENSE value 'mozilla_2_0' ignored" is emitted.

```
$ perl Makefile.PL
Checking if your kit is complete...
Looks good
Invalid LICENSE value 'mozilla_2_0' ignored
Generating a Unix-style Makefile
Writing Makefile for Mozilla::CA
Invalid LICENSE value 'mozilla_2_0' ignored
Writing MYMETA.yml and MYMETA.json
```

According to https://metacpan.org/pod/CPAN::Meta::Spec#license
we should set license "open_source" for MPL 2.0. 
I prepared a patch for this
https://gist.github.com/skaji/451bb3543a9cd631fa2070fe65cf8704

I'm willing to create a pull request to the github repository if you want.
Please let me know. Thanks.

```

From ask@perl.org on 2018-03-09 07:51:19
:
```
Hmn, itâs a little goofy to make it less specific, but if thatâs whatâs supported â sure, pull request would be helpful.
```

From rehsack@cpan.org on 2018-03-09 08:25:10
:
```
@Neil - you're bit better connected to the toolchain folks: what needs to be done to support Mozilla 2.0 license in EU::MM and Metacpan?
```

**Comment by haarg** [comment]
Fixed for next release.
